import { createClient } from '@supabase/supabase-js';

// These will be replaced with actual values from environment variables
const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL || '';
const supabaseAnonKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || '';

if (!supabaseUrl || !supabaseAnonKey) {
  console.warn('Missing Supabase environment variables. Please check your .env.local file.');
}

export const supabase = createClient(supabaseUrl, supabaseAnonKey, {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: true,
  },
});

// Storage bucket names
export const BUCKET_NAMES = {
  DOCUMENTS: 'documents',
} as const;

// File upload settings
export const UPLOAD_SETTINGS = {
  MAX_FILE_SIZE: 10 * 1024 * 1024, // 10MB
  ALLOWED_FILE_TYPES: [
    'application/pdf',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    'text/csv',
  ],
};

// Helper functions for storage
export const storageHelpers = {
  getFileExtension: (filename: string): string => {
    return filename.split('.').pop()?.toLowerCase() || '';
  },

  generateUniqueFilename: (filename: string): string => {
    const ext = storageHelpers.getFileExtension(filename);
    const timestamp = Date.now();
    const randomStr = Math.random().toString(36).substring(2, 10);
    return `${timestamp}_${randomStr}.${ext}`;
  },

  isFileTypeAllowed: (file: File): boolean => {
    return UPLOAD_SETTINGS.ALLOWED_FILE_TYPES.includes(file.type);
  },

  isFileSizeValid: (file: File): boolean => {
    return file.size <= UPLOAD_SETTINGS.MAX_FILE_SIZE;
  },
};

// Helper functions for tax calculations
export const taxHelpers = {
  calculateTaxBrackets: (income: number, brackets: any[]) => {
    let totalTax = 0;
    let remainingIncome = income;
    
    for (const bracket of brackets) {
      if (remainingIncome <= 0) break;
      
      const bracketIncome = Math.min(remainingIncome, bracket.max - bracket.min);
      totalTax += bracketIncome * (bracket.rate / 100);
      remainingIncome -= bracketIncome;
    }
    
    return totalTax;
  },
  
  optimizeDeductions: (expenses: any, standardDeduction: number) => {
    const itemizedTotal = Object.values(expenses).reduce((sum: number, expense: any) => sum + (expense || 0), 0);
    return itemizedTotal > standardDeduction ? 'itemized' : 'standard';
  },
  
  calculateEffectiveRate: (taxOwed: number, income: number) => {
    return income > 0 ? (taxOwed / income) * 100 : 0;
  },
  
  calculateMarginalRate: (income: number, brackets: any[]) => {
    for (const bracket of brackets) {
      if (income <= bracket.max) {
        return bracket.rate;
      }
    }
    return brackets[brackets.length - 1]?.rate || 0;
  }
};

// Database table types (will be generated by Supabase CLI)
export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id: string;
          email: string | null;
          country: string;
          filing_status: string;
          tax_scenarios: string[];
          created_at: string;
        };
        Insert: {
          id?: string;
          email?: string | null;
          country: string;
          filing_status: string;
          tax_scenarios?: string[];
          created_at?: string;
        };
        Update: {
          id?: string;
          email?: string | null;
          country?: string;
          filing_status?: string;
          tax_scenarios?: string[];
          created_at?: string;
        };
      };
      user_profiles: {
        Row: {
          id: string;
          user_id: string;
          birth_date: string | null;
          dependents: number;
          spouse_income: number;
          filing_status: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          birth_date?: string | null;
          dependents?: number;
          spouse_income?: number;
          filing_status: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          birth_date?: string | null;
          dependents?: number;
          spouse_income?: number;
          filing_status?: string;
          updated_at?: string;
        };
      };
      personal_finances: {
        Row: {
          id: string;
          user_id: string;
          salary_income: number;
          freelance_income: number;
          investment_income: number;
          rental_income: number;
          capital_gains: number;
          retirement_contributions: number;
          mortgage_interest: number;
          property_taxes: number;
          charitable_donations: number;
          medical_expenses: number;
          childcare_costs: number;
          education_expenses: number;
          other_deductions: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          salary_income?: number;
          freelance_income?: number;
          investment_income?: number;
          rental_income?: number;
          capital_gains?: number;
          retirement_contributions?: number;
          mortgage_interest?: number;
          property_taxes?: number;
          charitable_donations?: number;
          medical_expenses?: number;
          childcare_costs?: number;
          education_expenses?: number;
          other_deductions?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          salary_income?: number;
          freelance_income?: number;
          investment_income?: number;
          rental_income?: number;
          capital_gains?: number;
          retirement_contributions?: number;
          mortgage_interest?: number;
          property_taxes?: number;
          charitable_donations?: number;
          medical_expenses?: number;
          childcare_costs?: number;
          education_expenses?: number;
          other_deductions?: number;
          created_at?: string;
        };
      };
      businesses: {
        Row: {
          id: string;
          user_id: string;
          name: string;
          business_type: string;
          country: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          name: string;
          business_type: string;
          country: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          name?: string;
          business_type?: string;
          country?: string;
          created_at?: string;
        };
      };
      business_finances: {
        Row: {
          id: string;
          business_id: string;
          revenue: number;
          employee_costs: number;
          equipment: number;
          rent: number;
          utilities: number;
          marketing: number;
          travel_expenses: number;
          office_supplies: number;
          professional_services: number;
          insurance: number;
          other_expenses: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          business_id: string;
          revenue: number;
          employee_costs?: number;
          equipment?: number;
          rent?: number;
          utilities?: number;
          marketing?: number;
          travel_expenses?: number;
          office_supplies?: number;
          professional_services?: number;
          insurance?: number;
          other_expenses?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          business_id?: string;
          revenue?: number;
          employee_costs?: number;
          equipment?: number;
          rent?: number;
          utilities?: number;
          marketing?: number;
          travel_expenses?: number;
          office_supplies?: number;
          professional_services?: number;
          insurance?: number;
          other_expenses?: number;
          created_at?: string;
        };
      };
      tax_data: {
        Row: {
          id: string;
          country: string;
          personal_tax_brackets: any;
          corporate_tax_rate: number;
          standard_deduction: number;
          personal_deductions: any;
          business_deductions: any;
          tax_credits: any;
          retirement_limits: any;
          updated_at: string;
        };
        Insert: {
          id?: string;
          country: string;
          personal_tax_brackets: any;
          corporate_tax_rate: number;
          standard_deduction?: number;
          personal_deductions?: any;
          business_deductions?: any;
          tax_credits?: any;
          retirement_limits?: any;
          updated_at?: string;
        };
        Update: {
          id?: string;
          country?: string;
          personal_tax_brackets?: any;
          corporate_tax_rate?: number;
          standard_deduction?: number;
          personal_deductions?: any;
          business_deductions?: any;
          tax_credits?: any;
          retirement_limits?: any;
          updated_at?: string;
        };
      };
      comprehensive_analyses: {
        Row: {
          id: string;
          user_id: string;
          analysis_type: string;
          personal_summary: any;
          business_summary: any;
          combined_strategy: any;
          tax_optimization_plan: any;
          recommendations: any;
          tax_calendar: any;
          document_checklist: any;
          estimated_savings: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          analysis_type: string;
          personal_summary?: any;
          business_summary?: any;
          combined_strategy?: any;
          tax_optimization_plan: any;
          recommendations: any;
          tax_calendar?: any;
          document_checklist?: any;
          estimated_savings?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          analysis_type?: string;
          personal_summary?: any;
          business_summary?: any;
          combined_strategy?: any;
          tax_optimization_plan?: any;
          recommendations?: any;
          tax_calendar?: any;
          document_checklist?: any;
          estimated_savings?: number;
          created_at?: string;
        };
      };
    };
  };
}
