import { createClient } from '@supabase/supabase-js';
import type { Database } from './database.types';

// Read Vite env vars
const supabaseUrl = import.meta.env.VITE_SUPABASE_URL as string | undefined;
const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY as string | undefined;

// Fallback to hardcoded values for testing
const finalUrl = supabaseUrl || 'https://fiophmtlfuqswzinckxv.supabase.co';
const finalKey = supabaseAnonKey || 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZpb3BobXRsZnVxc3d6aW5ja3h2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4MTcyNDUsImV4cCI6MjA3MjM5MzI0NX0.4prqP1PkVt-6mB_dsoCfH06e0_sfXuFhE7hUmBWX5zs';

if (!supabaseUrl || !supabaseAnonKey) {
  console.warn('Using hardcoded Supabase values. Please set VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY in .env.local');
}

console.log('Supabase URL:', finalUrl);
console.log('Supabase Key present:', !!finalKey);

export const supabase = createClient<Database>(finalUrl, finalKey, {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: true,
  },
});


// Database table types (will be generated by Supabase CLI)
export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id: string;
          email: string | null;
          country: string;
          filing_status: string;
          tax_scenarios: string[];
          created_at: string;
        };
        Insert: {
          id?: string;
          email?: string | null;
          country: string;
          filing_status: string;
          tax_scenarios?: string[];
          created_at?: string;
        };
        Update: {
          id?: string;
          email?: string | null;
          country?: string;
          filing_status?: string;
          tax_scenarios?: string[];
          created_at?: string;
        };
      };
      user_profiles: {
        Row: {
          id: string;
          user_id: string;
          birth_date: string | null;
          dependents: number;
          spouse_income: number;
          filing_status: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          birth_date?: string | null;
          dependents?: number;
          spouse_income?: number;
          filing_status: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          birth_date?: string | null;
          dependents?: number;
          spouse_income?: number;
          filing_status?: string;
          updated_at?: string;
        };
      };
      personal_finances: {
        Row: {
          id: string;
          user_id: string;
          salary_income: number;
          freelance_income: number;
          investment_income: number;
          rental_income: number;
          capital_gains: number;
          retirement_contributions: number;
          mortgage_interest: number;
          property_taxes: number;
          charitable_donations: number;
          medical_expenses: number;
          childcare_costs: number;
          education_expenses: number;
          other_deductions: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          salary_income?: number;
          freelance_income?: number;
          investment_income?: number;
          rental_income?: number;
          capital_gains?: number;
          retirement_contributions?: number;
          mortgage_interest?: number;
          property_taxes?: number;
          charitable_donations?: number;
          medical_expenses?: number;
          childcare_costs?: number;
          education_expenses?: number;
          other_deductions?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          salary_income?: number;
          freelance_income?: number;
          investment_income?: number;
          rental_income?: number;
          capital_gains?: number;
          retirement_contributions?: number;
          mortgage_interest?: number;
          property_taxes?: number;
          charitable_donations?: number;
          medical_expenses?: number;
          childcare_costs?: number;
          education_expenses?: number;
          other_deductions?: number;
          created_at?: string;
        };
      };
      businesses: {
        Row: {
          id: string;
          user_id: string;
          name: string;
          business_type: string;
          country: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          name: string;
          business_type: string;
          country: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          name?: string;
          business_type?: string;
          country?: string;
          created_at?: string;
        };
      };
      business_finances: {
        Row: {
          id: string;
          business_id: string;
          revenue: number;
          employee_costs: number;
          equipment: number;
          rent: number;
          utilities: number;
          marketing: number;
          travel_expenses: number;
          office_supplies: number;
          professional_services: number;
          insurance: number;
          other_expenses: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          business_id: string;
          revenue: number;
          employee_costs?: number;
          equipment?: number;
          rent?: number;
          utilities?: number;
          marketing?: number;
          travel_expenses?: number;
          office_supplies?: number;
          professional_services?: number;
          insurance?: number;
          other_expenses?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          business_id?: string;
          revenue?: number;
          employee_costs?: number;
          equipment?: number;
          rent?: number;
          utilities?: number;
          marketing?: number;
          travel_expenses?: number;
          office_supplies?: number;
          professional_services?: number;
          insurance?: number;
          other_expenses?: number;
          created_at?: string;
        };
      };
      tax_data: {
        Row: {
          id: string;
          country: string;
          personal_tax_brackets: any;
          corporate_tax_rate: number;
          standard_deduction: number;
          personal_deductions: any;
          business_deductions: any;
          tax_credits: any;
          retirement_limits: any;
          updated_at: string;
        };
        Insert: {
          id?: string;
          country: string;
          personal_tax_brackets: any;
          corporate_tax_rate: number;
          standard_deduction?: number;
          personal_deductions?: any;
          business_deductions?: any;
          tax_credits?: any;
          retirement_limits?: any;
          updated_at?: string;
        };
        Update: {
          id?: string;
          country?: string;
          personal_tax_brackets?: any;
          corporate_tax_rate?: number;
          standard_deduction?: number;
          personal_deductions?: any;
          business_deductions?: any;
          tax_credits?: any;
          retirement_limits?: any;
          updated_at?: string;
        };
      };
      comprehensive_analyses: {
        Row: {
          id: string;
          user_id: string;
          analysis_type: string;
          personal_summary: any;
          business_summary: any;
          combined_strategy: any;
          tax_optimization_plan: any;
          recommendations: any;
          tax_calendar: any;
          document_checklist: any;
          estimated_savings: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          analysis_type: string;
          personal_summary?: any;
          business_summary?: any;
          combined_strategy?: any;
          tax_optimization_plan: any;
          recommendations: any;
          tax_calendar?: any;
          document_checklist?: any;
          estimated_savings?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          analysis_type?: string;
          personal_summary?: any;
          business_summary?: any;
          combined_strategy?: any;
          tax_optimization_plan?: any;
          recommendations?: any;
          tax_calendar?: any;
          document_checklist?: any;
          estimated_savings?: number;
          created_at?: string;
        };
      };
    };
  };
}
